# Generated by Django 3.1.6 on 2021-03-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pila',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('numLLantas', models.CharField(max_length=200)),
            ],
        ),
    ]
