# Generated by Django 3.1.6 on 2021-03-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pila', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pila',
            name='imagenes',
            field=models.ImageField(null=True, upload_to='imagenes'),
        ),
    ]
